name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Ruff lint
        run: |
          ruff --version
          ruff check . || true
      - name: Smoke import
        run: |
          python - <<'PY'
          import sys
          print('Python', sys.version)
          # Prefer public aliases
          from chatterbox import MurrTTS, MurrVC
          # Back-compat classes should also be importable
          from chatterbox.tts import ChatterboxTTS
          from chatterbox.vc import ChatterboxVC
          print('Imported MurrTTS/MurrVC and legacy classes OK')
          PY
